name: Fix Imports

on:
  workflow_dispatch:  # تشغيل يدوي
  push:
    branches: [ main ]

jobs:
  fix-imports:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Fix import files
      run: |
        cat > fix_imports.py << 'EOF'
        import os
        
        init_files = {
            "bot/__init__.py": '"""Bot package."""\n\n__version__ = "2.1.0"\n',
            "bot/core/__init__.py": '"""Core package."""\n\nplayer = None\n',
            "bot/helpers/__init__.py": '"""Helpers package."""\n',
            "bot/plugins/__init__.py": '"""Plugins package."""\n',
            "bot/persistence/__init__.py": '"""Persistence package."""\n',
        }
        
        for filepath, content in init_files.items():
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            with open(filepath, 'w') as f:
                f.write(content)
            print(f"Fixed: {filepath}")
        EOF
        
        python fix_imports.py
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-fix import files"
        git push
